### PR TITLE
Fix to redux-saga 1.0.0

### PR DESCRIPTION
**Pull request by misaku**
Fix to redux-saga 1.0.0
redux-saga 1.0.0 delete monitor and change interface, in dix pull i change to work new version

### CODE REVIEW

**Comment by asutula** [comment]
Awesome to see this is done, redux-saga 1.0 looks great :)

**Comment by misaku** [comment]
> Thank you @misaku!
> 
> I will be able to take a look at and test this tomorrow. If all goes well I will land this and get us supporting 1.0.0!

ok but thix pull fix crash, i will modify more for fix perfect an show perfect log

**Comment by misaku** [comment]
wait a momment i change all and a few minutes i will send

**Comment by misaku** [comment]
image

**Comment by misaku** [comment]
@rmevans9 did you look?

**Comment by rmevans9** [comment]
Sorry, not yet. I am pulling this all down right now to try it out and will see about landing this today.

**Comment by rmevans9** [comment]
This is actually in version 3.0.0!

**Pull request merged**
